---
- name: assert | Test cron_shell
  ansible.builtin.assert:
    quiet: true
    that:
      - cron_shell is defined
      - cron_shell is string
      - cron_shell is not none
- name: assert | Test cron_path
  ansible.builtin.assert:
    quiet: true
    that:
      - cron_path is defined
      - cron_path is string
      - cron_path is not none
- name: assert | Test cron_mailto
  ansible.builtin.assert:
    quiet: true
    that:
      - cron_mailto is defined
      - cron_mailto is string
      - cron_mailto is not none
- name: assert | Test cron_jobs
  ansible.builtin.assert:
    quiet: true
    that:
      - cron_jobs is iterable
  when:
    - cron_jobs is defined
- name: assert | Test item in cron_jobs
  ansible.builtin.assert:
    quiet: true
    that:
      - item.name is defined
      - item.name is string
      - item.name is not none
      - item.job is defined
      - item.job is string
      - item.job is not none
  loop: "{{ cron_jobs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - cron_jobs is defined
- name: assert | Test item.minute
  ansible.builtin.assert:
    quiet: true
    that:
      - item.minute >= 0
      - item.minute <= 59
  loop: "{{ cron_jobs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - cron_jobs is defined
    - item.minute is defined
    - item.minute is number
- name: assert | Test item.hour
  ansible.builtin.assert:
    quiet: true
    that:
      - item.hour >= 0
      - item.hour <= 23
  loop: "{{ cron_jobs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - cron_jobs is defined
    - item.hour is defined
    - item.hour is number
- name: assert | Test item.weekday
  ansible.builtin.assert:
    quiet: true
    that:
      - item.weekday >= 0
      - item.weekday <= 6
  loop: "{{ cron_jobs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - cron_jobs is defined
    - item.weekday is defined
    - item.weekday is number
